### ISSUE TITLE
La descarga no se termina

### ISSUE THREAD

**Issue by Mcalle25** [JakeFrostyYT/Pocohunter-chroot#2]
Aparece un mensaje diciendo "prohibido" y no puedo continuar con la descarga, uso Google Chrome.

**Comment by Mcalle25** [comment]
Hay algún otro link?

**Comment by JakeFrosty** [comment]
Yes there will be some new download options like Mega.nz and Google Drive, please wait until they are available,

**Comment by JakeFrosty** [comment]
I have updated the readme in the nethunter chroot main page, please select whichever you want
I will close this issue once i have confirmed that i have resolved your problems

**Comment by JakeFrosty** [comment]
You haven't replied in days, I'm gonna close this issue now
