### ISSUE TITLE
Having some issues with setup command

### ISSUE THREAD

**Issue by isonupandit11** [JakeFrostyYT/Pocohunter-chroot#3]
While running setup command I'm having following issues.
1....

E: Can't find a source to download version '2.7.17-2' of 'libpython-stdlib:arm64'
E: Can't find a source to download version '2.7.17-2' of 'python:arm64'
E: Can't find a source to download version '2.6.1-13' of 'python-crypto:arm64'
E: Can't find a source to download version '2.7.17-2' of 'python-minimal:arm64'
dpkg: error: cannot access archive '/etc/setup/*.deb': No such file or directory
rm: cannot remove '/etc/setup/*.deb': No such file or directory
![Screenshot_2020-11-26-15-51-18-35](https://user-images.githubusercontent.com/65156828/100344662-2e064800-3007-11eb-9928-24c43ad93e69.jpg)

2....
Failed to build NetfilterQueue and bluepy
![Screenshot_2020-11-26-15-51-38-85](https://user-images.githubusercontent.com/65156828/100344665-2fd00b80-3007-11eb-95d1-c9004e9f28ab.jpg)
![Screenshot_2020-11-26-15-51-41-02](https://user-images.githubusercontent.com/65156828/100344668-3199cf00-3007-11eb-9f84-df35f466d008.jpg)
![Screenshot_2020-11-26-15-52-27-73](https://user-images.githubusercontent.com/65156828/100344671-32cafc00-3007-11eb-9a83-f5a4e52c8ee5.jpg)

3....
Traceback (most recent call last):
  File "/etc/routersploit/setup.py", line 4, in <module>
    with open("README.md", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
![Screenshot_2020-11-26-15-59-10-46](https://user-images.githubusercontent.com/65156828/100344679-3494bf80-3007-11eb-9856-17b1ba5f0bf0.jpg)

4....
Nethunter-kex is all black only mouse cursor visible.
![Screenshot_2020-11-26-15-57-50-92](https://user-images.githubusercontent.com/65156828/100344677-33fc2900-3007-11eb-8749-fbdd318b9626.jpg)

**Comment by JakeFrosty** [comment]
This issue will be fixed, expect an update within the month of december

**Comment by JakeFrosty** [comment]
Sorry to say but, The fix will be delayed from december into january or february
